version: '3.4'

services:
  sanchez.blog:
    image: ${DOCKER_REGISTRY-}sanchezblog
    build:
      context: .
      dockerfile: Sanchez.Blog/Dockerfile
    ports:
      - "1024:80"
      - "2024:443"
    restart: always
